// Code Generated by Sidekick is for learning and experimentation purposes only.
require('dotenv').config();
const express = require("express");
const bodyParser = require("body-parser");
const axios = require("axios");

const app = express();

app.use(bodyParser.json());

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPO = "sdembi/Jira";

app.post("/webhook/jira", async (req, res) => {
  const event = req.body.webhookEvent;
  const issueKey = req.body.issue?.key;
  const changelog = req.body.changelog?.items;
  const issue = req.body.issue;

  // Status change detection
  if (event === "jira:issue_updated" && changelog) {
    for (const change of changelog) {
      if (change.field === "status") {
        console.log(
          `Status changed from ${change.fromString} to ${change.toString}`
        );

        // When status changes to "deployment needed"
        if (change.toString === "deployment needed") {
          console.log(
            `Triggering Salesforce deployment workflow for ${issueKey}`
          );

          // Extract Salesforce components and types from custom fields
          console.log(issue)
          const salesforceComponents =
            issue.fields.customfield_10058 || "";
          const componentTypes = issue.fields.customfield_10059 || "";
          const sandboxOrg = issue.fields.customfield_sandboxOrg || "dev";

          // // First create the branch
          // const branchName = `story/${issueKey}`;
          // console.log(`Creating branch: ${branchName}`);
          // await createBranch(branchName);

          // Then trigger the Salesforce deployment workflow
          await triggerSalesforceWorkflow(issueKey, {
            jira_ticket_key: issueKey,
            jira_status: change.toString,
            salesforce_components: salesforceComponents,
            component_types: componentTypes,
            sandbox_org: sandboxOrg,
          });
        }
      }
    }
  }
  res.status(200).send("Received");
});

// Function to trigger the Salesforce deployment workflow
async function triggerSalesforceWorkflow(issueKey, payload) {
  const headers = {
    Authorization: `token ${GITHUB_TOKEN}`,
    Accept: "application/vnd.github.v3+json",
  };

  try {
    console.log(
      "Attempting to trigger workflow with payload:",
      JSON.stringify(payload, null, 2)
    );

    // Send repository_dispatch event first as main trigger
    const dispatchUrl = `https://api.github.com/repos/${GITHUB_REPO}/dispatches`;
    await axios
      .post(
        dispatchUrl,
        {
          event_type: "jira-status-deployment-needed",
          client_payload: payload,
        },
        { headers }
      )
      .catch((error) => {
        console.error(
          "Repository dispatch failed:",
          error.response?.data || error.message
        );
        throw error;
      });

    console.log(`Successfully sent repository_dispatch event for ${issueKey}`);

    // Also try direct workflow trigger as backup
    try {
      const workflowUrl = `https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/workflow.yml/dispatches`;
      await axios.post(
        workflowUrl,
        {
          ref: "main",
          inputs: {
            jira_ticket_key: payload.jira_ticket_key || issueKey,
            jira_status: payload.jira_status || "deployment needed",
            salesforce_components: payload.salesforce_components || "none",
            component_types: payload.component_types || "none",
            sandbox_org: payload.sandbox_org || "dev",
          },
        },
        { headers }
      );
      console.log(`Also triggered workflow file directly for ${issueKey}`);
    } catch (workflowError) {
      console.log(
        "Direct workflow trigger failed (backup method):",
        workflowError.response?.data || workflowError.message
      );
      // Don't throw error for backup method
    }
  } catch (error) {
    console.error("Error triggering workflow:", {
      status: error.response?.status,
      statusText: error.response?.statusText,
      message: error.message,
      data: error.response?.data,
    });
    throw error;
  }
}

// Optionally, trigger a GitHub Actions workflow (via workflow_dispatch)
async function triggerGithubWorkflow(issueKey, branchName) {
  const workflowUrl = `https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/create-branch.yml/dispatches`;
  const headers = { Authorization: `token ${GITHUB_TOKEN}` };
  const data = {
    ref: "main", // Or default branch
    inputs: { issue_key: issueKey, branch_name: branchName },
  };
  return axios.post(workflowUrl, data, { headers });
}

app.listen(3000, () => console.log("Server running on 3000"));

