// Code Generated by Sidekick is for learning and experimentation purposes only.
const express = require("express");
const bodyParser = require("body-parser");
const axios = require("axios");

const app = express();

app.use(bodyParser.json());

const GITHUB_TOKEN = "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";
const GITHUB_REPO = "sdembi/Jira";

app.post("/webhook/jira", async (req, res) => {
  const event = req.body.webhookEvent;
  const issueKey = req.body.issue?.key;
  const changelog = req.body.changelog?.items;
  const issue = req.body.issue;

  // Status change detection
  if (event === "jira:issue_updated" && changelog) {
    for (const change of changelog) {
      if (change.field === "status") {
        console.log(
          `Status changed from ${change.fromString} to ${change.toString}`
        );

        // When status changes to "In Progress"
        if (change.toString === "In Progress") {
          console.log(
            `Triggering Salesforce deployment workflow for ${issueKey}`
          );

          // Extract Salesforce components and types from custom fields
          const salesforceComponents =
            issue.fields.customfield_salesforceComponents || "";
          const componentTypes = issue.fields.customfield_componentTypes || "";
          const sandboxOrg = issue.fields.customfield_sandboxOrg || "dev";

          // // First create the branch
          // const branchName = `story/${issueKey}`;
          // console.log(`Creating branch: ${branchName}`);
          // await createBranch(branchName);

          // Then trigger the Salesforce deployment workflow
          await triggerSalesforceWorkflow(issueKey, {
            jira_ticket_key: issueKey,
            jira_status: change.toString,
            salesforce_components: salesforceComponents,
            component_types: componentTypes,
            sandbox_org: sandboxOrg,
          });
        }
      }
    }
  }
  res.status(200).send("Received");
});

// // Directly create branch using GitHub API
// async function createBranch(branchName) {
//   try {
//     // Get default branch info
//     const repoUrl = `https://api.github.com/repos/${GITHUB_REPO}`;
//     const headers = { 
//       'Authorization': `token ${GITHUB_TOKEN}`,
//       'Accept': 'application/vnd.github.v3+json',
//       'Content-Type': 'application/json'
//     };

//     console.log(`Fetching repository information from ${repoUrl}`);
    
//     // Get default branch SHA
//     const repoRes = await axios.get(repoUrl, { headers });
//     const defaultBranch = repoRes.data.default_branch;
//     console.log(`Default branch is: ${defaultBranch}`);

//     // Get the SHA of the default branch using the correct endpoint
//     const refRes = await axios.get(`${repoUrl}/git/refs/heads/${defaultBranch}`, {
//       headers,
//     });
    
//     if (!refRes.data || !refRes.data.object || !refRes.data.object.sha) {
//       throw new Error(`Failed to get SHA for ${defaultBranch}. Response: ${JSON.stringify(refRes.data)}`);
//     }
    
//     const sha = refRes.data.object.sha;
//     console.log(`Got SHA: ${sha} from default branch ${defaultBranch}`);

//     // Check if branch already exists
//     try {
//       const branchCheck = await axios.get(`${repoUrl}/git/refs/heads/${branchName}`, { 
//         headers,
//         validateStatus: function (status) {
//           return status === 404 || status === 200; // Accept 404 as valid response
//         }
//       });
      
//       if (branchCheck.status === 200) {
//         console.log(`Branch ${branchName} already exists, skipping creation`);
//         return;
//       }
//     } catch (error) {
//       // If it's not a 404, something else went wrong
//       if (error.response?.status !== 404) {
//         throw error;
//       }
//     }

//     // Create new branch
//     console.log(`Creating new branch: ${branchName} from SHA: ${sha}`);
//     const createResponse = await axios.post(
//       `${repoUrl}/git/refs`,
//       {
//         ref: `refs/heads/${branchName}`,
//         sha: sha
//       },
//       { 
//         headers,
//         validateStatus: function (status) {
//           return status >= 200 && status < 300 || status === 422;
//         }
//       }
//     );

//     if (createResponse.status === 422) {
//       console.error('Branch creation failed. Response:', {
//         status: createResponse.status,
//         data: createResponse.data
//       });
//       throw new Error(`Failed to create branch: ${JSON.stringify(createResponse.data)}`);
//     }

//     console.log(`Successfully created branch: ${branchName}`);
//     return createResponse;
//   } catch (error) {
//     console.error('Error in createBranch:', {
//       message: error.message,
//       status: error.response?.status,
//       statusText: error.response?.statusText,
//       data: error.response?.data,
//       url: error.config?.url,
//       method: error.config?.method
//     });
//     throw error;
//   }
// }

// Function to trigger the Salesforce deployment workflow
async function triggerSalesforceWorkflow(issueKey, payload) {
  const headers = {
    Authorization: `token ${GITHUB_TOKEN}`,
    Accept: "application/vnd.github.v3+json",
  };

  try {
    console.log(
      "Attempting to trigger workflow with payload:",
      JSON.stringify(payload, null, 2)
    );

    // Send repository_dispatch event first as main trigger
    const dispatchUrl = `https://api.github.com/repos/${GITHUB_REPO}/dispatches`;
    await axios
      .post(
        dispatchUrl,
        {
          event_type: "jira-status-deployment-needed",
          client_payload: payload,
        },
        { headers }
      )
      .catch((error) => {
        console.error(
          "Repository dispatch failed:",
          error.response?.data || error.message
        );
        throw error;
      });

    console.log(`Successfully sent repository_dispatch event for ${issueKey}`);

    // Also try direct workflow trigger as backup
    try {
      const workflowUrl = `https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/workflow.yml/dispatches`;
      await axios.post(
        workflowUrl,
        {
          ref: "main",
          inputs: {
            jira_ticket_key: payload.jira_ticket_key || issueKey,
            jira_status: payload.jira_status || "In Progress",
            salesforce_components: payload.salesforce_components || "none",
            component_types: payload.component_types || "none",
            sandbox_org: payload.sandbox_org || "dev",
          },
        },
        { headers }
      );
      console.log(`Also triggered workflow file directly for ${issueKey}`);
    } catch (workflowError) {
      console.log(
        "Direct workflow trigger failed (backup method):",
        workflowError.response?.data || workflowError.message
      );
      // Don't throw error for backup method
    }
  } catch (error) {
    console.error("Error triggering workflow:", {
      status: error.response?.status,
      statusText: error.response?.statusText,
      message: error.message,
      data: error.response?.data,
    });
    throw error;
  }
}

// Optionally, trigger a GitHub Actions workflow (via workflow_dispatch)
async function triggerGithubWorkflow(issueKey, branchName) {
  const workflowUrl = `https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/create-branch.yml/dispatches`;
  const headers = { Authorization: `token ${GITHUB_TOKEN}` };
  const data = {
    ref: "main", // Or default branch
    inputs: { issue_key: issueKey, branch_name: branchName },
  };
  return axios.post(workflowUrl, data, { headers });
}

app.listen(3000, () => console.log("Server running on 3000"));
